services:
  api:
    container_name: back
    build: ./back/
    volumes:
      - ./back:/back
      - back_vendor:/back/vendor
    ports:
      - 8011:8000

  app:
    container_name: front
    build: ./front/
    volumes:
      - ./front:/front
      - front_node_modules:/front/node_modules
    ports:
      - 3011:3000

volumes:
  back_vendor:
    driver: local
  front_node_modules:
    driver: local
